Repository fga-eps-mds/2023.1-RelatorioGitPython, pull requests merged in 2023-06, with the labels that each got.

#44 Finalizando Função Média de Commits com Integração da API do GitHub
  .gitignore
  geradorrelatorio/average_commit.py
  geradorrelatorio/requirements.txt
Labels: backend, refactor, requirements

#45 Integração da API do GitHub na Função de Lista Arquivos por Extensão
  arquivo.md
  geradorrelatorio/main.py
  geradorrelatorio/verificar_tipo_arquivo.py
Labels: difícil, backend, refactor, requirements

#57 Relacionar usuário com o título dos commits
  src/main.py
  src/title_commits.py
Labels: fácil, backend, requirements

#58 Refatoracao biblioteca
  allcommits.txt
  arquivo_data.md
  arquivo_title.md
  src/gitInfo.py
  src/main.py
  tempCodeRunnerFile.python
Labels: backend, refactor
